era_movies = {
    "Showa Era": [
        ("Godzilla", 1954),
        "Godzilla Raids Again",
        "Rodan",
        "mothra",
        "King Kong vs. Godzilla",
        "Mothra vs. Godzilla",
        "Ghidorah, the Three-Headed Monster",
        "Invasion of Astro-Monster",
        "Ebirah, Horror of the Deep",
        "Son of Godzilla",
        "Destroy All Monsters",
        "All Monsters Attack",
        "Godzilla vs. Hedorah",
        "Godzilla vs. Gigan",
        "Godzilla vs. Megalon",
        "Godzilla vs. Mechagodzilla",
        "Terror of Mechagodzilla",
    ],
    "Heisei Era": [
        "The Return of Godzilla",
        "Godzilla vs. Biollante",
        "Godzilla vs. King Ghidorah",
        "Godzilla vs. Mothra",
        "Godzilla vs. Mechagodzilla II",
        "Godzilla vs. SpaceGodzilla",
        "Godzilla vs. Destoroyah",
    ],
    "Millennium Era": [
        "Godzilla 2000: Millennium",
        "Godzilla vs. Megaguirus",
        "Godzilla, Mothra and King Ghidorah: Giant Monsters All-Out Attack",
        "Godzilla Against Mechagodzilla",
        "Godzilla: Tokyo S.O.S.",
        "Godzilla: Final Wars",
    ],
    "Reiwa Era": [
        "Shin Godzilla",
        "Godzilla: Planet of the Monsters",
        "Godzilla: City on the Edge of Battle",
        "Godzilla: The Planet Eater",
        "Godzilla Singular Point",
        "Godzilla Minus One",
    ],
    "The MonsterVerse": [
        ("Godzilla", 2014),
        "Kong: Skull Island",
        "Godzilla: King of the Monsters",
        "Godzilla vs. Kong",
        "Monarch: Legacy of Monsters",
        "Godzilla x Kong: The New Empire",
    ],
    "misc": [
        "The Women of Godzilla",
        ("Godzilla", 1998),
        "Godzilla: The Series",
    ],

}
